# Generated by Django 2.2.5 on 2019-10-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logdate', models.CharField(max_length=5)),
                ('col_a', models.DecimalField(decimal_places=2, max_digits=20)),
                ('col_b', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pu', models.IntegerField(default=0)),
                ('arppu', models.IntegerField(default=0)),
                ('ret', models.DecimalField(decimal_places=2, max_digits=20)),
                ('output', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.IntegerField(default=0)),
                ('issuccess', models.IntegerField(default=0)),
                ('servicecountry', models.CharField(max_length=50)),
            ],
        ),
    ]
