# Generated by Django 2.2.5 on 2019-10-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logdate', models.TextField()),
                ('col_a', models.CharField(max_length=10)),
                ('col_b', models.CharField(max_length=10)),
                ('ret', models.FloatField()),
                ('output', models.FloatField()),
                ('total', models.IntegerField()),
                ('issuccess', models.BigIntegerField()),
                ('servicecountry', models.TextField()),
            ],
        ),
    ]
