# Generated by Django 2.2.5 on 2019-09-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
